{{- if .Values.auth.google.enabled }}
{{- if not .Values.auth.google.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "intelowl.fullname" . }}-google-oauth
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
    app.kubernetes.io/component: auth-google
type: Opaque
data:
  google-client-id: {{ .Values.auth.google.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.auth.google.clientSecret | b64enc | quote }}
{{- end }}
{{- end }}
