{{- if .Values.rbac.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "intelowl.serviceAccountName" . }}
  labels:
    {{- include "intelowl.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.migration.enabled }}
    {{- include "intelowl.installOrder" (dict "ctx" . "wave" "0" "weight" "-20") | nindent 4 }}
    {{- end }}
    {{- with .Values.rbac.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
